language: cpp

compiler:
  - clang++
  - g++
  
os:
  - linux
  
notifications:
  email: false
  
before_install:
  - psql -c "CREATE USER skateparks WITH PASSWORD 'skateparks';" -U postgres
  - echo $LANG
  - echo $LC_ALL

script:
  - ./build.sh
